// Renders every raster the product ships from two sources of truth — the SVG mark in
// public/favicon.svg and the real connect screen served from web/dist — so a rename or a new mark
// is one re-run, not a hunt through image files:
//
//   make brand                      # = make web && cd web && node dev/brand.mjs
//   BRAND_PORT=6832 pnpm brand      # port for the vite preview it starts
//
// Writes, in public/: favicon.png (96), apple-touch-icon.png (180), icon-192.png, icon-512.png and
// icon-maskable-512.png (mark inside the safe zone) — all five on the paper ground, because the
// mark is one colour of ink and a transparent PNG of it vanishes on dark chrome — and og.png
// (1200×630: the name, the one sentence, and the connect card as it renders); ../docs/media/
// mark-ink.svg and mark-paper.svg (the README's two flat marks, for <picture>); and
// ../.github/social-preview.png (1280×640, the same design at GitHub's size). Both cards are in
// the Swiss ink idiom (docs/brand/swiss-ink.md, ticket 038) and carry the two self-hosted faces
// inlined. The name and the sentence come from src/product.ts; the card is a screenshot, never a
// replica. No network.
import { spawn } from 'node:child_process';
import { readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, '..');
const pub = join(web, 'public');
const PORT = Number(process.env.BRAND_PORT ?? 6832);
const BASE = `http://127.0.0.1:${PORT}`;

const product = readFileSync(join(web, 'src/product.ts'), 'utf8');
const NAME = /PRODUCT_NAME = '([^']+)'/.exec(product)?.[1] ?? 'app';
const DESCRIPTION = /DESCRIPTION =\s*'([^']+)'/.exec(product)?.[1] ?? '';
const mark = readFileSync(join(pub, 'favicon.svg'), 'utf8');
// A well-formed invite for the card's field: the real shape (prefix, a 32-char tailcat address, a
// 43-char secret), so the card shows the screen a friend actually sees. Both halves are invented —
// no such host exists, the card is a screenshot, and nothing is ever sent.
const PREFIX = /INVITE_PREFIX = '([^']+)'/.exec(product)?.[1] ?? 'ic1';
const DEMO_INVITE = `${PREFIX}.tco2FwWCAw8jPY9xK4mR7bQvUz3Ld1Hn.T8kQz2mXvA5rNpJ7wEyLd3sHfBc9UgKi0oRtZ6xVn4M`;

// Mirror of the light :root tokens in src/styles.css (Swiss ink, 038). The cards are always the
// light half: a social card is shown on the reader's timeline, not in their colour scheme.
const P = { paper: '#ffffff', text: '#0a0a0a', muted: '#5c6068', border: '#d8dbe0', rule: '#0a0a0a' };

// The two faces the app ships, inlined so the composition needs no network and no installed font.
const FACES = [
  ['Archivo', '400 700', 'fonts/archivo-latin-var.woff2'],
  ['IBM Plex Mono', '400', 'fonts/ibm-plex-mono-400-latin.woff2'],
  ['IBM Plex Mono', '500', 'fonts/ibm-plex-mono-500-latin.woff2'],
];
const FACE_CSS = FACES.map(
  ([family, weight, file]) =>
    `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};src:url(data:font/woff2;base64,${readFileSync(join(pub, file)).toString('base64')}) format('woff2')}`,
).join('');
const FONT = "'Archivo', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";
const MONO = "'IBM Plex Mono', ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace";

// name, edge, ground (null = transparent), padding as a fraction of the edge on each side.
// Every raster carries the paper ground. The mark is one colour, and in this palette that colour is
// near-black ink: on a transparent ground the PNGs disappeared into a dark tab strip, a dark app
// list and the PWA install prompt (1.09:1 on Chrome's #202124). The SVG favicon still flips to
// paper on a dark scheme by its own media query; a rasterised PNG cannot, so it brings its paper
// with it — which is also what the two icons that were already opaque do.
const ICONS = [
  ['favicon.png', 96, P.paper, 0],
  ['apple-touch-icon.png', 180, P.paper, 0.1],
  ['icon-192.png', 192, P.paper, 0],
  ['icon-512.png', 512, P.paper, 0],
  ['icon-maskable-512.png', 512, P.paper, 0.2],
];

// The README's mark, as two flat one-colour files. GitHub chooses between them with <picture> and
// its own page theme; the `prefers-color-scheme` query inside favicon.svg resolves against the
// reader's OS instead, so an <img> of it puts a black cat on GitHub's dark canvas whenever the two
// disagree. Derived from the same SVG, so the mark contest still changes exactly one file.
const README_MARKS = [
  ['mark-ink.svg', 'ink'],
  ['mark-paper.svg', 'paper'],
];
const MARK_NOTE = `<!-- Generated by web/dev/brand.mjs from web/public/favicon.svg: the same geometry with the
       stylesheet flattened to one scheme (the favicon's light rules, or its dark rules applied on top).
       Do not edit by hand; run \`make brand\`. -->`;
// The favicon carries both schemes: base rules, then a prefers-color-scheme block that overrides them
// (a highlight class that the dark scheme hides, a stroke class for the tail). The README's two flat
// marks are those same rules with the media query removed: ink = the base rules; paper = base + dark.
const markStyle = mark.match(/<style>([\s\S]*?)<\/style>/)?.[1] ?? '';
const darkBlock = markStyle.match(/@media[^{]*\{([\s\S]*)\}\s*$/)?.[1] ?? '';
const baseRules = markStyle.replace(/@media[\s\S]*$/, '');
const flatMark = (scheme) =>
  mark
    .replace(/<style>[\s\S]*?<\/style>/, `<style>${baseRules}${scheme === 'paper' ? darkBlock : ''}</style>`)
    .replace(/<!--[\s\S]*?-->/, MARK_NOTE);

function iconPage(edge, ground, pad) {
  const inner = Math.round(edge * (1 - 2 * pad));
  return `<!doctype html><meta charset="utf-8"><style>
    html, body { margin: 0; width: ${edge}px; height: ${edge}px; overflow: hidden; background: ${ground ?? 'transparent'}; }
    body { display: grid; place-items: center; }
    svg { width: ${inner}px; height: ${inner}px; display: block; }
  </style>${mark}`;
}

/**
 * The card, in the Swiss ink idiom (038): ink on paper, no radius, no shadow, a 2 px ink rule over
 * the facts line, and the facts themselves in mono because they are claims about a machine. The
 * mark, the name and the sentence on the left; the connect screen — a screenshot, never a replica,
 * so the cobalt Connect on it is the app's own — framed in a hairline on the right.
 */
function cardPage(w, h, cardPng) {
  return `<!doctype html><meta charset="utf-8"><style>
    ${FACE_CSS}
    html, body { margin: 0; width: ${w}px; height: ${h}px; overflow: hidden; background: ${P.paper}; font-family: ${FONT}; }
    .left { position: absolute; left: 6%; top: 10.5%; width: 45%; }
    .mark { width: 54px; height: 54px; color: ${P.text}; }
    h1 { font-size: 92px; letter-spacing: -0.045em; line-height: 0.94; margin: 30px 0 22px; font-weight: 700; color: ${P.text}; }
    p { font-size: 26px; line-height: 1.34; color: ${P.muted}; margin: 0; max-width: 22ch; font-weight: 400; }
    .facts {
      position: absolute; left: 6%; bottom: 8.5%; width: 45%;
      border-top: 2px solid ${P.rule}; padding-top: 22px;
      font-family: ${MONO}; font-size: 19px; letter-spacing: 0.02em; color: ${P.text};
    }
    /* No frame of its own: the connect card carries the ink rectangle now, and two would be two. */
    .shot {
      position: absolute; left: 55%; top: 10.5%; bottom: 8.5%; width: 41%;
      overflow: hidden;
    }
    .shot img { width: 100%; height: 100%; object-fit: cover; object-position: top left; display: block; }
  </style>
  <div class="left">
    <div class="mark">${mark}</div>
    <h1>${NAME}</h1>
    <p>${DESCRIPTION}</p>
  </div>
  <div class="facts">Self-hosted · end-to-end encrypted · MIT</div>
  <div class="shot"><img src="data:image/png;base64,${cardPng.toString('base64')}" alt=""></div>`;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function waitFor(url) {
  for (let i = 0; i < 100; i++) {
    try {
      if ((await fetch(url)).ok) return;
    } catch {
      /* not up yet */
    }
    await sleep(200);
  }
  throw new Error(`nothing answered at ${url} — run \`make web\` first`);
}

const root = join(web, '..');
function report(file) {
  console.log(`  ${file.replace(`${root}/`, '')}  ${Math.round(statSync(file).size / 1024)} KB`);
}

async function main() {
  const browser = await chromium.launch();

  // 1. Icons, from the mark.
  for (const [name, edge, ground, pad] of ICONS) {
    const ctx = await browser.newContext({ viewport: { width: edge, height: edge }, deviceScaleFactor: 1, colorScheme: 'light' });
    const page = await ctx.newPage();
    await page.setContent(iconPage(edge, ground, pad));
    const file = join(pub, name);
    await page.screenshot({ path: file, omitBackground: ground === null });
    report(file);
    await ctx.close();
  }

  // 1b. The README's two flat marks (no browser needed: it is the same SVG with one fill).
  for (const [name, fill] of README_MARKS) {
    const file = join(web, '..', 'docs', 'media', name);
    writeFileSync(file, flatMark(fill));
    report(file);
  }

  // 2. The connect card, as the app renders it (light, 2× for crispness).
  const preview = spawn(process.execPath, ['node_modules/vite/bin/vite.js', 'preview', '--port', String(PORT), '--strictPort'], {
    cwd: web,
    stdio: ['ignore', 'ignore', 'inherit'],
  });
  try {
    await waitFor(`${BASE}/`);
    const ctx = await browser.newContext({ viewport: { width: 560, height: 900 }, deviceScaleFactor: 2, colorScheme: 'light' });
    const page = await ctx.newPage();
    await page.goto(`${BASE}/`);
    await page.waitForSelector('.connect-card');
    // The card is shown in the state the reader arrives at with a code in hand: the field carries a
    // well-formed invite (this address does not exist), so Connect is the enabled cobalt button the
    // brand calls for rather than a disabled one, and the focus ring is not mistaken for a border.
    await page.fill('.connect textarea', DEMO_INVITE);
    await page.evaluate(() => document.activeElement?.blur());
    await page.evaluate(() => document.fonts.ready);
    await page.waitForTimeout(200);
    const cardPng = await page.locator('.connect-card').screenshot();
    await ctx.close();

    // 3. The two cards, composed from the pieces above.
    for (const [file, w, h] of [
      [join(pub, 'og.png'), 1200, 630],
      [join(web, '..', '.github', 'social-preview.png'), 1280, 640],
    ]) {
      const c = await browser.newContext({ viewport: { width: w, height: h }, deviceScaleFactor: 1, colorScheme: 'light' });
      const p = await c.newPage();
      await p.setContent(cardPage(w, h, cardPng));
      await p.evaluate(() => document.fonts.ready);
      await p.screenshot({ path: file });
      report(file);
      await c.close();
    }
  } finally {
    preview.kill('SIGTERM');
  }
  await browser.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
