// Rebuild the icons, flat README marks, and two social cards from the shared SVG/fonts.
// make brand; the site speaks to friends, the GitHub card to hosts (ticket 050).
import { readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, '..');
const pub = join(web, 'public');
const product = readFileSync(join(web, 'src/product.ts'), 'utf8');
const NAME = /PRODUCT_NAME = '([^']+)'/.exec(product)?.[1] ?? 'app';
const mark = readFileSync(join(pub, 'favicon.svg'), 'utf8');
// Mirror of the light :root tokens in src/styles.css (Swiss ink, 038). The cards are always the
// light half: a social card is shown on the reader's timeline, not in their colour scheme.
const P = { paper: '#ffffff', text: '#0a0a0a', muted: '#5c6068', border: '#d8dbe0', rule: '#0a0a0a' };

// The two faces the app ships, inlined so the composition needs no network and no installed font.
const FACES = [
  ['Archivo', '400 700', 'fonts/archivo-latin-var.woff2'],
  ['IBM Plex Mono', '400', 'fonts/ibm-plex-mono-400-latin.woff2'],
  ['IBM Plex Mono', '500', 'fonts/ibm-plex-mono-500-latin.woff2'],
];
const FACE_CSS = FACES.map(
  ([family, weight, file]) =>
    `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};src:url(data:font/woff2;base64,${readFileSync(join(pub, file)).toString('base64')}) format('woff2')}`,
).join('');
const FONT = "'Archivo', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";
const MONO = "'IBM Plex Mono', ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace";

// name, edge, ground (null = transparent), padding as a fraction of the edge on each side.
// Every raster carries the paper ground. The mark is one colour, and in this palette that colour is
// near-black ink: on a transparent ground the PNGs disappeared into a dark tab strip, a dark app
// list and the PWA install prompt (1.09:1 on Chrome's #202124). The SVG favicon still flips to
// paper on a dark scheme by its own media query; a rasterised PNG cannot, so it brings its paper
// with it — which is also what the two icons that were already opaque do.
const ICONS = [
  ['favicon.png', 96, P.paper, 0],
  ['apple-touch-icon.png', 180, P.paper, 0.1],
  ['icon-192.png', 192, P.paper, 0],
  ['icon-512.png', 512, P.paper, 0],
  ['icon-maskable-512.png', 512, P.paper, 0.2],
];

// The README's mark, as two flat one-colour files. GitHub chooses between them with <picture> and
// its own page theme; the `prefers-color-scheme` query inside favicon.svg resolves against the
// reader's OS instead, so an <img> of it puts a black cat on GitHub's dark canvas whenever the two
// disagree. Derived from the same SVG, so the mark contest still changes exactly one file.
const README_MARKS = [
  ['mark-ink.svg', 'ink'],
  ['mark-paper.svg', 'paper'],
];
const MARK_NOTE = `<!-- Generated by web/dev/brand.mjs from web/public/favicon.svg: the same geometry with the
       stylesheet flattened to one scheme (the favicon's light rules, or its dark rules applied on top).
       Do not edit by hand; run \`make brand\`. -->`;
// The favicon carries both schemes: base rules, then a prefers-color-scheme block that overrides them
// (a highlight class that the dark scheme hides, a stroke class for the tail). The README's two flat
// marks are those same rules with the media query removed: ink = the base rules; paper = base + dark.
const markStyle = mark.match(/<style>([\s\S]*?)<\/style>/)?.[1] ?? '';
const darkBlock = markStyle.match(/@media[^{]*\{([\s\S]*)\}\s*$/)?.[1] ?? '';
const baseRules = markStyle.replace(/@media[\s\S]*$/, '');
const flatMark = (scheme) =>
  mark
    .replace(/<style>[\s\S]*?<\/style>/, `<style>${baseRules}${scheme === 'paper' ? darkBlock : ''}</style>`)
    .replace(/<!--[\s\S]*?-->/, MARK_NOTE);

function iconPage(edge, ground, pad) {
  const inner = Math.round(edge * (1 - 2 * pad));
  return `<!doctype html><meta charset="utf-8"><style>
    html, body { margin: 0; width: ${edge}px; height: ${edge}px; overflow: hidden; background: ${ground ?? 'transparent'}; }
    body { display: grid; place-items: center; }
    svg { width: ${inner}px; height: ${inner}px; display: block; }
  </style>${mark}`;
}

// The measured bottom-row axis and x-height centres match the approved 050 sheet.
function cardPage(w, h, lines, heroTop) {
  const axis = h - 80, markLeft = 80 - 0.169 * 88;
  const hero = `${lines[0]}<br>${lines[1]}<span class="cobalt">.</span>`;
  return `<!doctype html><meta charset="utf-8"><style>
    ${FACE_CSS}
    html,body{margin:0;width:${w}px;height:${h}px;overflow:hidden;background:${P.paper};color:${P.text};font-family:${FONT};-webkit-font-smoothing:antialiased}
    *{box-sizing:border-box}
    .hero{position:absolute;left:74px;top:${heroTop}px;margin:0;font-size:160px;font-weight:700;letter-spacing:-.04em;line-height:.95;white-space:nowrap}
    .cobalt{color:#1f3bff}
    .rule{position:absolute;left:80px;right:80px;top:${h - 156}px;height:1px;background:${P.rule}}
    .mark{position:absolute;left:${markLeft.toFixed(1)}px;top:${(axis - .532 * 88).toFixed(1)}px;width:88px;height:88px}
    .mark svg{display:block;width:100%;height:100%}
    .sig{position:absolute;left:${(markLeft + .956 * 88 + 28).toFixed(1)}px;top:${(axis + .526 * 66 / 2 - .834 * 66).toFixed(1)}px;font-size:66px;font-weight:700;letter-spacing:-.035em;line-height:1;white-space:nowrap}
    .facts{position:absolute;right:80px;top:${(axis + .516 * 27 / 2 - .825 * 27).toFixed(1)}px;font-family:${MONO};font-weight:400;font-size:27px;line-height:1;white-space:nowrap}
  </style><h1 class="hero">${hero}</h1><div class="rule"></div>
  <div class="mark">${mark}</div><div class="sig">${NAME}</div>
  <div class="facts">Self-hosted · end-to-end encrypted · MIT</div>`;
}

const root = join(web, '..');
function report(file) {
  console.log(`  ${file.replace(`${root}/`, '')}  ${Math.round(statSync(file).size / 1024)} KB`);
}

async function main() {
  const browser = await chromium.launch();

  // 1. Icons, from the mark.
  for (const [name, edge, ground, pad] of ICONS) {
    const ctx = await browser.newContext({ viewport: { width: edge, height: edge }, deviceScaleFactor: 1, colorScheme: 'light' });
    const page = await ctx.newPage();
    await page.setContent(iconPage(edge, ground, pad));
    const file = join(pub, name);
    await page.screenshot({ path: file, omitBackground: ground === null });
    report(file);
    await ctx.close();
  }

  // 1b. The README's two flat marks (no browser needed: it is the same SVG with one fill).
  for (const [name, fill] of README_MARKS) {
    const file = join(web, '..', 'docs', 'media', name);
    writeFileSync(file, flatMark(fill));
    report(file);
  }

  // One composition, the approved sentence and hard breaks for each audience.
  for (const [file, w, h, lines, top] of [
    [join(pub, 'og.png'), 1200, 630, ['Chat with a', 'friend’s GPU'], 126],
    [join(web, '..', '.github', 'social-preview.png'), 1280, 640, ['Let friends chat', 'with your GPU'], 120],
  ]) {
    const ctx = await browser.newContext({ viewport: { width: w, height: h }, deviceScaleFactor: 1, colorScheme: 'light' });
    const page = await ctx.newPage();
    await page.setContent(cardPage(w, h, lines, top));
    await page.evaluate(() => document.fonts.ready);
    await page.screenshot({ path: file });
    report(file);
    await ctx.close();
  }
  await browser.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
