export const copy = {
  stored_agent: ["agent", "智能体"],
  stored_image_kind: ["image", "图片"],
  stored_queued: ["queued", "排队中"],
  stored_running: ["running", "运行中"],
  stored_waiting: ["waiting", "等待中"],
  stored_done: ["done", "已完成"],
  stored_failed: ["failed", "已失败"],
  stored_cancelled: ["cancelled", "已取消"],

  stored_timeout: ["The host took too long to answer. Try refreshing.", "主机响应超时。请刷新后重试。"],
  stored_read_failed: ["Could not read stored data from the host. Try refreshing.", "无法读取主机保存的数据。请刷新后重试。"],
  stored_unknown: ["No answer from the host. Clearing may have completed. Check the refreshed list. Nothing was sent again.", "主机没有响应。清理可能已经完成。请检查刷新后的列表。操作没有再次发送。"],
  stored: ["Stored", "已保存"],
  stored_loading: ["Reading stored data…", "正在读取保存的数据…"],
  stored_summary: ["{0} runs · {1} images · {2} kept", "{0} 次运行 · {1} 张图片 · 已保存 {2}"],
  stored_expires: ["oldest expires in {0} days", "最早将在 {0} 天后过期"],
  stored_expired: ["expiry reached", "已到期"],
  stored_reserved: ["Live-run reservations: {0}.", "进行中运行的预留空间：{0}。"],
  stored_excess: ["Above the ordinary ceiling: {0}.", "超出常规上限：{0}。"],
  stored_budget: ["Run state: {0} / {1}. Images: {2} / {3}.", "运行数据：{0} / {1}。图片：{2} / {3}。"],
  stored_kind: ["{0} stored · {1} live", "已保存 {0} 次 · 进行中 {1} 次"],
  stored_range: ["Expiry: {0} to {1}", "过期时间：{0} 至 {1}"],
  stored_orphan: ["{0} untracked file for review — the host never deletes these", "{0} 个未跟踪文件待检查——主机不会删除这些文件"],
  stored_orphans: ["{0} untracked files for review — the host never deletes these", "{0} 个未跟踪文件待检查——主机不会删除这些文件"],
  stored_cleanup: ["{0} files awaiting cleanup", "{0} 个文件等待清理"],
  stored_image: ["Image: {0} · expires {1}", "图片：{0} · {1} 过期"],
  stored_truncated: ["Showing {0} of {1} runs.", "显示 {1} 次运行中的 {0} 次。"],
  stored_sizes: ["Run sizes include their retained content; shared event metadata is included only in the total.", "每次运行的大小包含其保留内容；共享事件元数据只计入总量。"],
  stored_clear: ["Clear stored data for this key", "清除此密钥保存的数据"],
  stored_confirm: ["Delete up to {0} finished runs and their retained content{1}?", "删除最多 {0} 次已结束运行及其保留内容{1}？"],
  stored_confirm_one: ["Delete up to {0} finished run and its retained content{1}?", "删除最多 {0} 次已结束运行及其保留内容{1}？"],
  stored_confirm_images: [", including up to {0} images", "（含最多 {0} 张图片）"],
  stored_confirm_image: [", including up to {0} image", "（含最多 {0} 张图片）"],
  stored_confirm_retry: ["Retry cleanup of up to {0} files.", "重试清理最多 {0} 个文件。"],
  stored_confirm_retry_one: ["Retry cleanup of up to {0} file.", "重试清理最多 {0} 个文件。"],
  stored_keep_live: ["Live runs and outstanding work stay.", "进行中的运行和未完成的工作会保留。"],
  stored_retried: ["Retried cleanup of {0} files.", "已重试清理 {0} 个文件。"],
  stored_retried_one: ["Retried cleanup of {0} file.", "已重试清理 {0} 个文件。"],
  stored_cleanup_one: ["{0} file awaiting cleanup", "{0} 个文件等待清理"],
  stored_cleared_one: ["Cleared {0} finished run; {1} with outstanding work kept.", "已清除 {0} 次已结束运行；保留了 {1} 次仍有未完成工作的运行。"],
  stored_cleared: ["Cleared {0} finished runs; {1} with outstanding work kept.", "已清除 {0} 次已结束运行；保留了 {1} 次仍有未完成工作的运行。"],
  stored_clear_yes: ["Clear finished data", "清除已结束的数据"],

  f_public: ["Public URL", "公开网址"],
  pub_on: ["on · connected since {0}", "开启 · {0} 起已连接"],
  pub_reconnecting: ["on · not connected", "开启 · 未连接"],
  pub_error: ["on · not connected · {0}", "开启 · 未连接 · {0}"],
  pub_off: ["off", "已关闭"],
  pub_today: ["{0} requests today", "今天 {0} 次请求"],
  u_via_tunnel: ["Through the tunnel", "经隧道"],
  u_via_public: ["Through the public URL", "经公开网址"],
  via_value: ["{0} calls · {1} tokens", "{0} 次调用 · {1} token"],
  u_audio: ["Audio seconds", "音频秒数"],
  u_speech: ["Speech characters", "语音字符数"],
  audio_s: ["{0} s", "{0} 秒"],
  audio_chars: ["{0} chars", "{0} 字符"],

  connected: ["connected", "已连接"],
  devices: ["{0} devices", "{0} 台设备"],
  connected_count: ["{0} connected", "{0} 把密钥已连接"],
  remote_recovery: ["Remote access is off: {0} is unreadable or invalid. Turn remote access on again to mint a new code.", "远程访问已关闭：{0} 无法读取或内容无效。请重新开启远程访问以生成新的管理码。"],
  remote_pill: ["through the tunnel", "经隧道"],
  remote_suffix: ["remote", "远程"],
  forget_console: ["Forget this console", "忘记这个控制台"],
  remote_refused: ["This admin code was refused. Open a fresh code from the host.", "这个管理码被拒绝。请在主机上获取新的管理码。"],
  remote_closed: ["Closed · observed at {0}. Nothing here answers any more; the console is still on the host.", "已关闭 · 在 {0} 观察到。这里不再有任何响应；控制台仍在主机上。"],
  remote_budget: ["Too many console requests — try again in {0} s. The action was not retried.", "控制台请求过多——请在 {0} 秒后重试。操作没有自动重试。"],
  remote_address: ["not from here · --console, on the host", "不能在这里更改 · 请在主机上使用 --console"],
  remote_here: ["you are on the tunnel now — turning this off ends this session too", "你现在就在隧道上——关闭也会结束这个会话"],
  admin_send_live: ["Open the link on your phone. The web app reads ia1 and opens this console instead of a chat.", "在手机上打开这个链接。网页版读到 ia1，会打开这个控制台，而不是聊天。"],

  admin_meta: ["this console · through the tunnel", "这个控制台 · 经隧道"],
  admin_copy: ["Copy code", "复制管理码"],
  one_change: ["1 change · invites already sent keep working — they carry the code, not the URL", "1 项修改 · 已发出的邀请码仍然有效——它们携带的是码，不是网址"],
  settings_lead: ["Each field says when it applies. Nothing here restarts the host.", "每一项都写清何时生效。这里的任何操作都不会重启主机。"],
  changed_live: ["changed · applies at once when saved", "已修改 · 保存后立即生效"],
  changed_next: ["changed · waits for the host’s next start", "已修改 · 等待主机下次启动"],
  name_live: ["in force — friends see it on their next poll", "已生效——朋友下一次轮询就能看到"],
  web_live: ["in force for the next link you copy", "对你下一次复制的链接生效"],
  log_live: ["at once · this run only · not remembered — pass --log-requests next time", "立即生效 · 仅本次运行 · 不保存——下次请传入 --log-requests"],
  slots_next: ["when the host next starts · running with {0}", "主机下次启动时生效 · 当前运行值为 {0}"],
  console_next: ["when the host next starts · serving on {0} until then", "主机下次启动时生效 · 在此之前由 {0} 提供服务"],
  saved_time: ["saved {0}", "{0} 已保存"],
  url_refusal: ["not https — whoever answers that address can read the code in the link", "不是 https——回应这个地址的人能读到链接里的邀请码"],
  url_preview: ["links would print as {0}", "链接会写成 {0}"],
  web_hint: ["Where the links you copy open. Empty means the built-in web app.", "你复制的链接打开的地方。留空用内置的网页版。"],
  console_address: ["Console address", "控制台地址"],
  console_hint: ["Where this page is served on the host. Loopback only; off disables it.", "这个页面在主机上的位置。只在回环地址上；off 表示关闭。"],
  settings_saved: ["saved · each field shows when it applies", "已保存 · 每一项都显示何时生效"],
  changes: ["{0} changes · invites already sent keep working — they carry the code, not the URL", "{0} 项修改 · 已发出的邀请码仍然有效——它们携带的是码，不是网址"],
  remote_access: ["Remote access", "远程访问"],
  remote_switch: ["Reach this console through the tunnel", "经隧道打开这个控制台"],
  remote_hint: ["Off: this page is served on this machine only. On: an admin code opens the console API through the tunnel.", "关：这个页面只在这台机器上提供。开：管理码可经隧道打开控制台接口。"],
  remote_trust: ["Anyone with the admin code controls this host’s keys — mint, pause, revoke, limits. It is shown once; turning this off ends every remote session at once.", "拿到管理码的人就掌握了这台主机的密钥——生成、暂停、撤销、限额。它只显示一次；关掉这个开关会立刻结束所有远程会话。"],
  remote_since: ["on since {0}", "{0} 起开启"],
  in_use: ["in use", "使用中"],
  not_in_use: ["not in use", "未使用"],
  rotate_code: ["Rotate code", "换发管理码"],
  turn_off: ["Turn off", "关闭"],
  keep_on: ["Keep on", "保持开启"],
  off_confirm: ["Turning off ends every remote session now and the admin code stops working. This page stays on this machine.", "关闭会立刻结束所有远程会话，管理码随即失效。这个页面仍在这台机器上。"],
  never_heading: ["Even through the tunnel, this console never", "即使经隧道，这个控制台也从不"],
  never_prompts: ["reads prompts", "读取提示词"],
  never_prompts_why: ["The console API returns counts, never prompt text. --log-prompts stays a host-side flag.", "控制台接口只返回数字，从不返回提示词内容。--log-prompts 仍是主机上的参数。"],
  never_engine: ["changes the engine URL", "更改引擎地址"],
  never_engine_why: ["The engine is what friends reach. Changing it belongs on the host, with --upstream.", "朋友连接的是这个引擎。更改它应在主机上使用 --upstream。"],
  never_address: ["changes the console address", "更改控制台地址"],
  never_address_why: ["Not remotely: moving the listener would strand this session. Use --console on the host.", "不能远程更改：移动监听地址会断开这个会话。请在主机上使用 --console。"],
  admin_title: ["Admin code", "管理码"],
  admin_new: ["New admin code", "新管理码"],
  admin_trust: ["Whoever has this code controls {0}’s keys. It is for your other devices; send it to no one.", "拿到这串码的人就掌握了 {0} 的密钥。它是给你自己其他设备用的；不要发给任何人。"],
  admin_opens: ["What it opens", "它能打开什么"],
  admin_scope: ["Keys, limits and settings. Never prompts, the engine URL or the console address. Not a chat key — it answers no /v1 request.", "密钥、限额和设置。从不提供提示词、引擎地址或控制台地址。它不是聊天密钥——不响应任何 /v1 请求。"],
  admin_lost: ["Lost it later? Rotate code issues a new one and ends every session on the old.", "以后弄丢了？换发管理码会生成新的，并结束旧码上的所有会话。"],

  engine_ceiling: ["the engine ceiling", "引擎上限"],
  mint_submit: ["Mint", "生成"],
  minted_now: ["minted just now", "刚刚生成"],
  rotate_title: ["{0}’s new invite", "{0} 的新邀请码"],
  rotated_line: ["the previous invite no longer works", "之前那串已经失效"],
  no_web: ["No web app URL is set, so there is no link: {0} pastes the code into the web app.", "没有设置网页版地址，所以没有链接：{0} 把邀请码粘贴到网页版就行。"],
  lost_h: ["Lost it later? Rotate issues a new one and retires this.", "以后弄丢了？换发会生成新的并作废这一串。"],
  minted_limits: ["Change these any time from {0}’s row; changes take effect at once.", "随时可以从 {0} 那一行改；改完立刻生效。"],

  new_name: ["Name", "名称"],
  name_hint: ["One person. A second device is a second key: alice-laptop.", "一个人一把。第二台设备就再生成一把：alice-laptop。"],
  once_title: ["{0}’s invite", "{0} 的邀请码"],
  once_tag: ["Shown once", "只显示一次"],
  once_p: ["Only its hash is stored. Copy it now; closing this drawer is the last time it is on a screen.", "只保存哈希。现在就复制；关掉这个抽屉，它就不会再出现在任何屏幕上。"],
  copy_link: ["Copy link", "复制链接"],
  copy_code: ["Copy code", "复制邀请码"],
  copied: ["Copied", "已复制"],
  send_p: ["Send {0} the link. Their browser opens the web app with the code filled in; the code alone works too.", "把链接发给 {0}。浏览器会打开网页版，邀请码已填好；只发邀请码也行。"],
  scan: ["Scan to open", "扫码打开"],
  done: ["Done", "完成"],
  keep: ["Keep", "保留"],
  revoke_q: ["Revoking is permanent — {0} would need a new invite. Pause stops them temporarily instead.", "撤销是永久的——{0} 需要新的邀请码。暂停则只是暂时停止。"],
  revoke_yes: ["Revoke {0}", "撤销 {0}"],
  in_force: ["In force at once — no restart, nothing for {0} to do.", "立即生效——无需重启，{0} 无需操作。"],
  pause_h: ["Pause answers {0} with 403 until you resume; their chats stay on their device. Rotate mints a new invite and retires this one — the drawer shows it once.", "暂停后，{0} 会收到 403，直到你恢复；聊天仍保存在对方设备上。换发会生成新邀请码并使旧的失效——抽屉只显示一次。"],
  working: ["Waiting for the host…", "正在等待主机…"],
  saved_limits: ["Limits saved.", "限额已保存。"],
  unknown_write: ["No answer from the host. The action may have completed. Check the refreshed row before trying again; rotate if an invite was lost.", "主机没有响应。操作可能已完成。重试前请检查刷新的行；如果邀请码丢失，请换发。"],
  refresh_write: ["The action completed; waiting for a fresh view from the host.", "操作已完成；正在等待主机的最新状态。"],
  qr_failed: ["QR unavailable. The code and link still work.", "二维码不可用。邀请码和链接仍然有效。"],
  copy_failed: ["Could not copy. Select and copy the code or link.", "复制失败。请选中并复制邀请码或链接。"],
  l_audio: ["Audio seconds per day", "每天音频秒数"],
  l_speech: ["Speech characters per day", "每天语音字符数"],
  models_hint: ["No selection means all models.", "不选择表示全部模型。"],
  limit_hint: ["0 means unlimited, except context: 0 uses the engine ceiling. Mint uses CLI defaults for zero values.", "0 表示不限，上下文除外：0 使用引擎上限。生成时，零值使用命令行默认值。"],

  pinned: ["pinned", "已固定"],
  console: ["Console", "控制台"],
  on_machine: ["on this machine", "本机"],
  ix_friends: ["Friends", "朋友"],
  ix_engine: ["Engine", "引擎"],
  ix_usage: ["Usage", "用量"],
  ix_settings: ["Settings", "设置"],
  healthy: ["healthy", "正常"],
  f_engine: ["Engine", "引擎"],
  f_tunnel: ["Tunnel", "隧道"],
  relay: ["relay", "中继"],
  f_now: ["Right now", "此刻"],
  f_today: ["Today", "今天"],
  friends: ["Friends", "朋友"],
  friends_lead: ["One key is one person. Limits live on the key — a key is a budget, not a seat.", "一把密钥对应一个人。限额挂在密钥上——密钥是一份额度，不是一个座位。"],
  mint: ["Mint an invite", "生成邀请码"],
  th_friend: ["Friend", "朋友"],
  th_status: ["Status", "状态"],
  th_now: ["Now", "此刻"],
  th_today: ["Today", "今天"],
  th_limits: ["Limits", "限额"],
  th_seen: ["Last seen", "上次使用"],
  s_active: ["active", "启用"],
  s_paused: ["paused", "已暂停"],
  s_revoked: ["revoked", "已撤销"],
  counts_line: ["rpm counts model calls and the app's /v1/models lookup; tpm and tokens per day count model calls only.", "rpm 统计模型调用和网页版的 /v1/models 查询；tpm 与每日 token 只统计模型调用。"],
  engine: ["Engine", "引擎"],
  e_kind: ["Kind", "类型"],
  e_health: ["Health", "状态"],
  e_slots: ["Slots", "处理位"],
  e_ctx: ["Context", "上下文"],
  e_ctx_s: ["tokens · the ceiling for every key", "token · 所有密钥的上限"],
  e_tps: ["Throughput", "吞吐"],
  e_tps_s: ["completion tokens, last minute", "输出 token，最近一分钟"],
  e_says: ["Engine says", "引擎报告"],
  e_says_s: ["from /metrics", "来自 /metrics"],
  e_mem: ["Memory", "内存"],
  e_peak: ["Peak", "峰值"],
  e_peak_s: ["sampled once a second", "每秒抽样一次"],
  m_model: ["Model", "模型"],
  m_ctx: ["Context", "上下文"],
  m_calls: ["Calls today", "今日调用"],
  m_keys: ["Open to", "开放给"],
  engine_foot: ["Infercat never starts or stops an engine. What is listed is what the engine at this address answers with; a key's model allowlist picks from it.", "Infercat 从不启动或停止引擎。这里列出的是这个地址上的引擎自己报告的；密钥的模型白名单从中挑选。"],
  usage: ["Usage", "用量"],
  usage_src: ["counts, never text · from usage.jsonl · UTC days", "只记数字，不记文字 · 读自 usage.jsonl · 按 UTC 日"],
  u_today: ["Today", "今天"],
  u_week: ["7 days", "7 天"],
  u_calls: ["Model calls", "模型调用"],
  u_polls: ["App polls", "网页版轮询"],
  u_polls_s: ["/me and /v1/models, what a browser does on its own", "/me 和 /v1/models，浏览器自己发的"],
  u_err: ["Errors", "错误"],
  u_prompt: ["Prompt tokens", "输入 token"],
  u_compl: ["Completion tokens", "输出 token"],
  u_ttft: ["Time to first token", "首 token 耗时"],
  u_total: ["Total time", "总耗时"],
  u_total_s: ["p50 · p95, successful model calls only", "p50 · p95，只算成功的模型调用"],
  days_cap: ["Tokens per day · prompt + completion", "每天的 token · 输入 + 输出"],
  usage_foot: ["Per friend, today, is in the table above; per friend over the week is in each friend's drawer.", "每个朋友今天的用量在上面的表里；一周的在各自的抽屉里。"],
  settings: ["Settings", "设置"],
  st_name: ["Name", "名称"],
  st_name_h: ["What your friends see as the host.", "朋友看到的主机名。"],
  st_web: ["Web app URL", "网页版地址"],
  st_web_h: ["Invites print as <url>#<invite>. Empty means the built-in one.", "邀请码会写成 <地址>#<邀请码>。留空用内置的。"],
  st_slots: ["Slots", "处理位"],
  st_log: ["Log requests", "记录请求"],
  st_log_h: ["One line per completed request on the host's terminal: who, route, tokens, timings, how it ended. Never prompt content.", "每个完成的请求在主机终端打一行：谁、接口、token 数、耗时、怎么结束的。从不记录提示词内容。"],
  save: ["Save", "保存"],
  ro_data: ["Data dir", "数据目录"],
  ro_data_s: ["keys.json · usage.jsonl · host key", "keys.json · usage.jsonl · 主机密钥"],
  ro_up: ["Engine URL", "引擎地址"],
  ro_up_s: ["detected at start · --upstream to pin", "启动时自动检测 · --upstream 可固定"],
  ro_relay: ["Relay", "中继"],
  ro_relay_s: ["--derpmap-url to run your own", "--derpmap-url 可换成你自己的"],
  source: ["Source on GitHub", "GitHub 源码"],
  made: ["Made by 2185 Lab", "2185 Lab 出品"],
  close: ["Close", "关闭"],
  created: ["created", "创建于"],
  d_now: ["Now", "此刻"],
  d_limits: ["Limits", "限额"],
  l_rpm: ["Requests per minute", "每分钟请求数"],
  l_tpm: ["Tokens per minute", "每分钟 token 数"],
  l_conc: ["At once", "同时进行"],
  l_out: ["Max output tokens", "单次回复上限"],
  l_ctx: ["Context", "上下文"],
  l_daily: ["Tokens per day", "每天 token 数"],
  l_models: ["Models", "模型"],
  save_limits: ["Save limits", "保存限额"],
  d_usage: ["Usage", "用量"],
  u_tokens: ["Tokens in → out", "token 输入 → 输出"],
  u_ttft50: ["Time to first token p50", "首 token p50"],
  u_lastcall: ["Last model call", "上次模型调用"],
  d_key: ["Key", "密钥"],
  pause: ["Pause", "暂停"],
  rotate: ["Rotate", "换发"],
  revoke: ["Revoke", "撤销"],
  resume: ["Resume", "恢复"],
  not_reported: ["not reported", "未报告"],
  unknown: ["(not identified yet)", "（尚未识别）"],
  loading: ["Reading the host…", "正在读取主机…"],
  need_token: ["Open this page with infercat console on the host.", "请在主机上运行 infercat console 打开此页。"],
  stale: ["no answer from the host for {0} s — still trying", "主机 {0} 秒没有响应——仍在重试"],
  refreshed: ["live · refreshed {0} s ago", "实时 · {0} 秒前刷新"],
  down: ["NOT ANSWERING for {0}", "{0} 无响应"],
  degraded: ["{0} at {1} is not answering — friends see “engine offline” until it is back.", "{1} 上的 {0} 没有响应——恢复之前，朋友那边显示“引擎已离线”。"],
  engine_sub: ["{0} slots · {1} context", "{0} 个处理位 · {1} 上下文"],
  tunnel_sub: ["{0} connected · in {1} · out {2}", "{0} 个已连接 · 收 {1} · 发 {2}"],
  right_now: ["{0} in flight · {1} waiting", "{0} 条进行中 · {1} 条排队"],
  in_flight: ["{0} in flight", "{0} 条进行中"],
  throughput: ["{0} tok/s over the last minute", "最近一分钟 {0} tok/s"],
  today_value: ["{0} model calls · {1} tokens", "{0} 次模型调用 · {1} token"],
  today_sub: ["{0} errors · ttft p50 {1}", "{0} 次错误 · 首 token p50 {1}"],
  friends_count: ["{0} keys · {1} active · {2} paused", "{0} 把密钥 · {1} 个启用 · {2} 个暂停"],
  no_keys: ["No keys yet — mint one and send your first friend the link.", "还没有密钥——生成一串邀请码，把链接发给第一个朋友。"],
  idle: ["idle", "空闲"],
  minute: ["{0}/{1} this minute", "本分钟 {0}/{1}"],
  limits: ["{0} rpm · {1} tpm · {2} at once · {3} out", "{0} rpm · {1} tpm · 同时 {2} 条 · 单次 {3}"],
  all_models: ["all models", "全部模型"],
  one_model: ["{0} only", "仅 {0}"],
  n_models: ["{0} of {1} models", "{1} 个模型中的 {0} 个"],
  never: ["never", "从未"],
  just_now: ["just now", "刚刚"],
  ago: ["{0} ago", "{0} 前"],
  revoked_n: ["{0} revoked keys", "{0} 把已撤销的密钥"],
  since: ["since {0} · probed {1}", "已持续 {0} · {1} 探测"],
  slots_auto: ["from the engine · no --slots override", "引擎给出 · 没有 --slots 覆盖"],
  slots_override: ["--slots override", "--slots 覆盖"],
  metrics: ["{0} busy · {1} waiting", "{0} 忙碌 · {1} 等待"],
  no_metrics: ["no /metrics from this engine", "这个引擎没有 /metrics"],
  kv: ["kv cache {0}%", "kv 缓存 {0}%"],
  open_all: ["all {0} keys", "全部 {0} 把密钥"],
  open_to: ["{0} of {1} keys", "{1} 把密钥中的 {0} 把"],
  no_usage: ["nothing yet", "还没有"],
  no_calls: ["no recorded calls", "没有记录到调用"],
  calls: ["{0} calls", "{0} 次调用"],
  malformed: ["{0} unreadable lines in the log were skipped", "日志里有 {0} 行读不出来，已跳过"],
  settings_src: ["config.json in {0}", "{0} 里的 config.json"],
  slots_hint: ["Parallel requests the engine can serve. 0 asks the engine.", "引擎能同时处理的请求数。0 表示问引擎。"],
  restart: ["Read-only · settings apply on restart", "只读 · 设置在重启时生效"],
  default_relay: ["default map · region auto", "默认中继表 · 区域自动"],
  prompts_off: ["Prompt logging is off. It is a flag on serve, never a setting here — and when it is on, the web app tells your friends.", "提示词日志已关闭。它是 serve 的一个参数，从来不是这里的设置——开启时，网页版会告诉你的朋友。"],
  prompts_on: ["Prompt logging is on for this run (--log-prompts). Your friends’ web app says so.", "本次运行已开启提示词日志（--log-prompts）。朋友的网页版会显示。"],
  tpm: ["{0}/{1} tpm", "本分钟 {0}/{1} token"],
  tokens_today: ["{0}/{1} tokens today", "今天 {0}/{1} token"],
  context_hint: ["0 = the engine ceiling, {0} today.", "0 = 引擎上限，今天是 {0}。"],
  hash_only: ["Only the invite’s hash is stored. Lost? Rotate issues a new one.", "只保存邀请码的哈希。弄丢了？换发会生成新的。"],
  effective_web: ["Effective web app URL: {0}", "实际网页版地址：{0}"],
  not_remembered: ["not remembered", "不保存"],
} as const;
export type CopyKey = keyof typeof copy;
export type Lang = "en" | "zh";
export function text(lang: Lang, key: CopyKey, ...args: (string | number)[]): string {
 return copy[key][lang === "zh" ? 1 : 0].replace(/\{(\d+)\}/g, (_, i) => String(args[Number(i)] ?? ""));
}
