export const copy = {
  pinned: ["pinned", "已固定"],
  console: ["Console", "控制台"],
  on_machine: ["on this machine", "本机"],
  ix_friends: ["Friends", "朋友"],
  ix_engine: ["Engine", "引擎"],
  ix_usage: ["Usage", "用量"],
  ix_settings: ["Settings", "设置"],
  healthy: ["healthy", "正常"],
  f_engine: ["Engine", "引擎"],
  f_tunnel: ["Tunnel", "隧道"],
  relay: ["relay", "中继"],
  f_now: ["Right now", "此刻"],
  f_today: ["Today", "今天"],
  friends: ["Friends", "朋友"],
  friends_lead: ["One key is one person. Limits live on the key — a key is a budget, not a seat.", "一把密钥对应一个人。限额挂在密钥上——密钥是一份额度，不是一个座位。"],
  mint: ["Mint an invite", "生成邀请码"],
  th_friend: ["Friend", "朋友"],
  th_status: ["Status", "状态"],
  th_now: ["Now", "此刻"],
  th_today: ["Today", "今天"],
  th_limits: ["Limits", "限额"],
  th_seen: ["Last seen", "上次使用"],
  s_active: ["active", "启用"],
  s_paused: ["paused", "已暂停"],
  s_revoked: ["revoked", "已撤销"],
  counts_line: ["rpm counts model calls and the app's /v1/models lookup; tpm and tokens per day count model calls only.", "rpm 统计模型调用和网页版的 /v1/models 查询；tpm 与每日 token 只统计模型调用。"],
  engine: ["Engine", "引擎"],
  detected: ["detected", "自动检测"],
  e_kind: ["Kind", "类型"],
  e_health: ["Health", "状态"],
  e_slots: ["Slots", "处理位"],
  e_ctx: ["Context", "上下文"],
  e_ctx_s: ["tokens · the ceiling for every key", "token · 所有密钥的上限"],
  e_tps: ["Throughput", "吞吐"],
  e_tps_s: ["completion tokens, last minute", "输出 token，最近一分钟"],
  e_says: ["Engine says", "引擎报告"],
  e_says_s: ["from /metrics", "来自 /metrics"],
  e_mem: ["Memory", "内存"],
  e_peak: ["Peak", "峰值"],
  e_peak_s: ["sampled once a second", "每秒抽样一次"],
  m_model: ["Model", "模型"],
  m_ctx: ["Context", "上下文"],
  m_calls: ["Calls today", "今日调用"],
  m_keys: ["Open to", "开放给"],
  engine_foot: ["Infercat never starts or stops an engine. What is listed is what the engine at this address answers with; a key's model allowlist picks from it.", "Infercat 从不启动或停止引擎。这里列出的是这个地址上的引擎自己报告的；密钥的模型白名单从中挑选。"],
  usage: ["Usage", "用量"],
  usage_src: ["counts, never text · from usage.jsonl · UTC days", "只记数字，不记文字 · 读自 usage.jsonl · 按 UTC 日"],
  u_today: ["Today", "今天"],
  u_week: ["7 days", "7 天"],
  u_calls: ["Model calls", "模型调用"],
  u_polls: ["App polls", "网页版轮询"],
  u_polls_s: ["/me and /v1/models, what a browser does on its own", "/me 和 /v1/models，浏览器自己发的"],
  u_err: ["Errors", "错误"],
  u_prompt: ["Prompt tokens", "输入 token"],
  u_compl: ["Completion tokens", "输出 token"],
  u_ttft: ["Time to first token", "首 token 耗时"],
  u_total: ["Total time", "总耗时"],
  u_total_s: ["p50 · p95, successful model calls only", "p50 · p95，只算成功的模型调用"],
  days_cap: ["Tokens per day · prompt + completion", "每天的 token · 输入 + 输出"],
  usage_foot: ["Per friend, today, is in the table above; per friend over the week is in each friend's drawer.", "每个朋友今天的用量在上面的表里；一周的在各自的抽屉里。"],
  settings: ["Settings", "设置"],
  st_name: ["Name", "名称"],
  st_name_h: ["What your friends see as the host.", "朋友看到的主机名。"],
  st_web: ["Web app URL", "网页版地址"],
  st_web_h: ["Invites print as <url>#<invite>. Empty means the built-in one.", "邀请码会写成 <地址>#<邀请码>。留空用内置的。"],
  st_slots: ["Slots", "处理位"],
  st_log: ["Log requests", "记录请求"],
  st_log_h: ["One line per completed request on the host's terminal: who, route, tokens, timings, how it ended. Never prompt content.", "每个完成的请求在主机终端打一行：谁、接口、token 数、耗时、怎么结束的。从不记录提示词内容。"],
  save: ["Save", "保存"],
  ro_data: ["Data dir", "数据目录"],
  ro_data_s: ["keys.json · usage.jsonl · host key", "keys.json · usage.jsonl · 主机密钥"],
  ro_up: ["Engine URL", "引擎地址"],
  ro_up_s: ["detected at start · --upstream to pin", "启动时自动检测 · --upstream 可固定"],
  ro_relay: ["Relay", "中继"],
  ro_relay_s: ["--derpmap-url to run your own", "--derpmap-url 可换成你自己的"],
  source: ["Source on GitHub", "GitHub 源码"],
  made: ["Made by 2185 Lab", "2185 Lab 出品"],
  close: ["Close", "关闭"],
  created: ["created", "创建于"],
  d_now: ["Now", "此刻"],
  d_limits: ["Limits", "限额"],
  l_rpm: ["Requests per minute", "每分钟请求数"],
  l_tpm: ["Tokens per minute", "每分钟 token 数"],
  l_conc: ["At once", "同时进行"],
  l_out: ["Max output tokens", "单次回复上限"],
  l_ctx: ["Context", "上下文"],
  l_daily: ["Tokens per day", "每天 token 数"],
  l_models: ["Models", "模型"],
  save_limits: ["Save limits", "保存限额"],
  d_usage: ["Usage", "用量"],
  u_tokens: ["Tokens in → out", "token 输入 → 输出"],
  u_ttft50: ["Time to first token p50", "首 token p50"],
  u_lastcall: ["Last model call", "上次模型调用"],
  d_key: ["Key", "密钥"],
  pause: ["Pause", "暂停"],
  rotate: ["Rotate", "换发"],
  revoke: ["Revoke", "撤销"],
  resume: ["Resume", "恢复"],
  not_reported: ["not reported", "未报告"],
  unknown: ["(not identified yet)", "（尚未识别）"],
  loading: ["Reading the host…", "正在读取主机…"],
  need_token: ["Open this page with infercat console on the host.", "请在主机上运行 infercat console 打开此页。"],
  stale: ["no answer from the host for {0} s — still trying", "主机 {0} 秒没有响应——仍在重试"],
  refreshed: ["live · refreshed {0} s ago", "实时 · {0} 秒前刷新"],
  down: ["NOT ANSWERING for {0}", "{0} 无响应"],
  degraded: ["{0} at {1} is not answering — friends see “engine offline” until it is back.", "{1} 上的 {0} 没有响应——恢复之前，朋友那边显示“引擎已离线”。"],
  engine_sub: ["{0} slots · {1} context", "{0} 个处理位 · {1} 上下文"],
  tunnel_sub: ["{0} connected · in {1} · out {2}", "{0} 个已连接 · 收 {1} · 发 {2}"],
  right_now: ["{0} in flight · {1} waiting", "{0} 条进行中 · {1} 条排队"],
  in_flight: ["{0} in flight", "{0} 条进行中"],
  throughput: ["{0} tok/s over the last minute", "最近一分钟 {0} tok/s"],
  today_value: ["{0} model calls · {1} tokens", "{0} 次模型调用 · {1} token"],
  today_sub: ["{0} errors · ttft p50 {1}", "{0} 次错误 · 首 token p50 {1}"],
  friends_count: ["{0} keys · {1} active · {2} paused", "{0} 把密钥 · {1} 个启用 · {2} 个暂停"],
  no_keys: ["No keys yet — mint one and send your first friend the link.", "还没有密钥——生成一串邀请码，把链接发给第一个朋友。"],
  idle: ["idle", "空闲"],
  minute: ["{0}/{1} this minute", "本分钟 {0}/{1}"],
  limits: ["{0} rpm · {1} tpm · {2} at once · {3} out", "{0} rpm · {1} tpm · 同时 {2} 条 · 单次 {3}"],
  all_models: ["all models", "全部模型"],
  one_model: ["{0} only", "仅 {0}"],
  n_models: ["{0} of {1} models", "{1} 个模型中的 {0} 个"],
  never: ["never", "从未"],
  just_now: ["just now", "刚刚"],
  ago: ["{0} ago", "{0} 前"],
  revoked_n: ["{0} revoked keys", "{0} 把已撤销的密钥"],
  since: ["since {0} · probed {1}", "已持续 {0} · {1} 探测"],
  slots_auto: ["from the engine · no --slots override", "引擎给出 · 没有 --slots 覆盖"],
  slots_override: ["--slots override", "--slots 覆盖"],
  metrics: ["{0} busy · {1} waiting", "{0} 忙碌 · {1} 等待"],
  no_metrics: ["no /metrics from this engine", "这个引擎没有 /metrics"],
  kv: ["kv cache {0}%", "kv 缓存 {0}%"],
  open_all: ["all {0} keys", "全部 {0} 把密钥"],
  open_to: ["{0} of {1} keys", "{1} 把密钥中的 {0} 把"],
  no_usage: ["nothing yet", "还没有"],
  no_calls: ["no recorded calls", "没有记录到调用"],
  calls: ["{0} calls", "{0} 次调用"],
  malformed: ["{0} unreadable lines in the log were skipped", "日志里有 {0} 行读不出来，已跳过"],
  settings_src: ["config.json in {0}", "{0} 里的 config.json"],
  slots_hint: ["Parallel requests the engine can serve. 0 asks the engine.", "引擎能同时处理的请求数。0 表示问引擎。"],
  restart: ["Read-only · settings apply on restart", "只读 · 设置在重启时生效"],
  default_relay: ["default map · region auto", "默认中继表 · 区域自动"],
  prompts_off: ["Prompt logging is off. It is a flag on serve, never a setting here — and when it is on, the web app tells your friends.", "提示词日志已关闭。它是 serve 的一个参数，从来不是这里的设置——开启时，网页版会告诉你的朋友。"],
  prompts_on: ["Prompt logging is on for this run (--log-prompts). Your friends’ web app says so.", "本次运行已开启提示词日志（--log-prompts）。朋友的网页版会显示。"],
  readonly: ["Read-only.", "只读。"],
  tpm: ["{0}/{1} tpm", "本分钟 {0}/{1} token"],
  tokens_today: ["{0}/{1} tokens today", "今天 {0}/{1} token"],
  context_hint: ["0 = the engine ceiling, {0} today.", "0 = 引擎上限，今天是 {0}。"],
  hash_only: ["Only the invite’s hash is stored. Lost? Rotate issues a new one.", "只保存邀请码的哈希。弄丢了？换发会生成新的。"],
  effective_web: ["Effective web app URL: {0}", "实际网页版地址：{0}"],
  not_remembered: ["not remembered", "不保存"],
} as const;
export type CopyKey = keyof typeof copy;
export type Lang = "en" | "zh";
export function text(lang: Lang, key: CopyKey, ...args: (string | number)[]): string {
 return copy[key][lang === "zh" ? 1 : 0].replace(/\{(\d+)\}/g, (_, i) => String(args[Number(i)] ?? ""));
}
