// @vitest-environment jsdom
import {test,expect,vi,afterEach} from 'vitest';
import {createConsole} from './app';
import fixture from './test/fixture.json';
let app;afterEach(()=>{app?.stop();vi.useRealTimers();});
async function setup(initialStatus=200){vi.useFakeTimers();document.body.innerHTML='<div id="app"></div>';let status=initialStatus;const data=structuredClone(fixture);Object.assign(data.settings,{writes_supported:true,console_address:'127.0.0.1:9101',configured_console:'127.0.0.1:9101',remote:{enabled:true,in_use:true}});
 const calls=[],request=vi.fn(async(url,init)=>{calls.push({url,init});if(status!==200)return new Response('refused',{status,headers:{'Retry-After':'10'}});return new Response(JSON.stringify(url.includes('window=today')?data.today:url.includes('window=week')?data.week:data[url.slice(5)]));});const view={path:'relayed · 84 ms',leave:vi.fn()};app=createConsole(document.querySelector('#app'),'memory-only',request,Date.now,undefined,view);await vi.advanceTimersByTimeAsync(0);return {calls,view,setStatus:n=>{status=n;}};}
for(const status of [401,404])test(`remote ${status} stops reads with truthful terminal copy`,async()=>{const s=await setup();s.setStatus(status);await app.refresh();expect(document.body.textContent).toContain(status===401?'This admin code was refused':'Closed · observed at');const n=s.calls.length;await vi.advanceTimersByTimeAsync(20000);expect(s.calls).toHaveLength(n);expect(document.querySelector('main').hasAttribute('inert')).toBe(true);});
test('remote polling honors Retry-After and never sends writes itself',async()=>{const s=await setup();s.setStatus(429);await app.refresh();const n=s.calls.length;expect(document.body.textContent).toContain('Too many console requests');await vi.advanceTimersByTimeAsync(8000);expect(s.calls).toHaveLength(n);s.setStatus(200);await vi.advanceTimersByTimeAsync(4000);expect(s.calls.length).toBeGreaterThan(n);expect(s.calls.every(x=>!x.init.method)).toBe(true);});
test('remote address is a fact, not a form field; storage stays empty',async()=>{await setup();expect(document.querySelector('#setting-console')).toBeNull();expect(document.body.textContent).toContain('not from here');expect(localStorage.length+sessionStorage.length).toBe(0);});

for(const status of [401,404])test(`initial remote ${status} shows the terminal state without a snapshot`,async()=>{const s=await setup(status);expect(document.body.textContent).toContain(status===401?'This admin code was refused':'Closed · observed at');const n=s.calls.length;await vi.advanceTimersByTimeAsync(12000);expect(s.calls).toHaveLength(n);});
test('a refused write shows the approved budget line and is never replayed',async()=>{const s=await setup();document.querySelector('[data-key]').click();s.setStatus(429);document.querySelector('[data-action="pause"]').click();await vi.advanceTimersByTimeAsync(0);expect(document.body.textContent).toContain('The action was not retried.');await vi.advanceTimersByTimeAsync(12000);expect(s.calls.filter(c=>c.init.method)).toHaveLength(1);});
